Fix build of PHP 7.0 image
Installation of zip via "pecl install" is no longer working, causing the
following error:

configure: error: Please reinstall the libzip distribution
ERROR: `/var/tmp/zip/configure --with-php-config=/usr/bin/php-config'
failed

Fixing the problem by installing it through rpm package.